### PR TITLE
Feat - Add .env.sample file, sample request

### PR DESCRIPTION
**Pull request by yoniihdc**
#### What does this PR do?
This PR includes a sample request for bot, and the `.env.sample` file to store our environment variables.

#### Where should the reviewer start?
* `index.js`
* `src/bot.js`
* `.env.sample`

#### How should this be manually tested?
Clone this repo, create `.env` file, fill the variables with the sample data, and run, it should deploy in your localhost in the selected port.

### CODE REVIEW

**Comment by yoniihdc** [comment]
@PabloFer13 we are testing this and as far this project goes to be our main introduction platform we want to use strict standards of node js. If you think the code is ok, can you help me with an approval 👍  please

**Comment by tugorez** [comment]
@yoniihdc i think the .env* files must not commited, I think is a better idea to describe it in the README.

**Comment by yoniihdc** [comment]
@tugorez this is not the real `.env` file, this is just a copy without sensitive information, this information must be passed outside this repo.

**Comment by tugorez** [comment]
Yeah but, why commit it in the project?

**Comment by yoniihdc** [comment]
In order to take all these variables saved in somewhere instead of out of the project and avoid issues related to them, maybe it isn't best practices but could work as a guide to create instead of start modifying  README file which is more public than this sample file.

**Pull request merged**
